### ISSUE TITLE
Warning: Division by zero

### ISSUE THREAD

**Issue by chrom** [AOEpeople/Aoe_Profiler#64]
```
Warning: Division by zero  in app/code/community/Aoe/Profiler/Model/Run.php on line 135

#0 app/code/community/Aoe/Profiler/Model/Run.php(135): mageCoreErrorHandler(2, 'Division by zer...', '/Users/andreyza...', 135, Array)
#1 app/code/community/Aoe/Profiler/Model/Run.php(77): Aoe_Profiler_Model_Run->calcRelativeValues()
#2 app/code/community/Aoe/Profiler/Block/Tree.php(140): Aoe_Profiler_Model_Run->processRawData()
#3 app/code/core/Mage/Core/Block/Abstract.php(890): Aoe_Profiler_Block_Tree->_toHtml()
#4 app/code/core/Mage/Core/Block/Abstract.php(609): Mage_Core_Block_Abstract->toHtml()
#5 app/code/core/Mage/Core/Block/Abstract.php(553): Mage_Core_Block_Abstract->_getChildHtml('aoe_profiler_tr...', true)
#6 app/design/adminhtml/default/default/template/aoe_profiler/view.phtml(19): Mage_Core_Block_Abstract->getChildHtml('aoe_profiler_tr...')
#7 app/code/core/Mage/Core/Block/Template.php(247): include('/Users/andreyza...')
#8 app/code/core/Mage/Core/Block/Template.php(279): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#9 app/code/core/Mage/Core/Block/Template.php(293): Mage_Core_Block_Template->renderView()
#10 app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#11 app/code/core/Mage/Adminhtml/Block/Widget/Container.php(308): Mage_Adminhtml_Block_Template->_toHtml()
#12 app/code/core/Mage/Core/Block/Abstract.php(890): Mage_Adminhtml_Block_Widget_Container->_toHtml()
#13 app/code/core/Mage/Core/Block/Text/List.php(46): Mage_Core_Block_Abstract->toHtml()
#14 app/code/core/Mage/Core/Block/Abstract.php(890): Mage_Core_Block_Text_List->_toHtml()
#15 app/code/core/Mage/Core/Block/Abstract.php(609): Mage_Core_Block_Abstract->toHtml()
#16 app/code/core/Mage/Core/Block/Abstract.php(553): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#17 app/design/adminhtml/default/default/template/page.phtml(74): Mage_Core_Block_Abstract->getChildHtml('content')
#18 app/code/core/Mage/Core/Block/Template.php(247): include('/Users/andreyza...')
#19 app/code/core/Mage/Core/Block/Template.php(279): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#20 app/code/core/Mage/Core/Block/Template.php(293): Mage_Core_Block_Template->renderView()
#21 app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#22 app/code/core/Mage/Core/Block/Abstract.php(890): Mage_Adminhtml_Block_Template->_toHtml()
#23 app/code/local/Inchoo/PHP7/Model/Layout.php(15): Mage_Core_Block_Abstract->toHtml()
#24 app/code/core/Mage/Core/Controller/Varien/Action.php(390): Inchoo_PHP7_Model_Layout->getOutput()
#25 app/code/community/Aoe/Profiler/controllers/Adminhtml/ProfilerController.php(130): Mage_Core_Controller_Varien_Action->renderLayout()
#26 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Aoe_Profiler_Adminhtml_ProfilerController->viewAction()
#27 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('view')
#28 app/code/core/Mage/Core/Controller/Varien/Front.php(174): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#29 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#30 app/Mage.php(685): Mage_Core_Model_App->run(Array)
#31 index.php(228): Mage::run('', 'store')
#32 {main}
```

**Comment by devspelunk** [comment]
I'm also experiencing this issue. Has there been any feedback?

**Comment by ProxiBlue** [comment]
@devspelunk @chrom 

See: https://github.com/AOEpeople/Aoe_Profiler/pull/70

Either of you using https://github.com/colinmollenhour/Cm_RedisSession?

**Comment by tylerssn** [comment]
Did anyone happen to get to the bottom of this?
